// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNqtgTjLOQLiaw_zsZp0rIonsB2GQKJf0',
    appId: '1:299896259972:web:0c1cd0fe553204549849d1',
    messagingSenderId: '299896259972',
    projectId: 'gtms-fd7f3',
    authDomain: 'gtms-fd7f3.firebaseapp.com',
    databaseURL: 'https://gtms-fd7f3-default-rtdb.firebaseio.com',
    storageBucket: 'gtms-fd7f3.appspot.com',
    measurementId: 'G-HGP0DJDR9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLhFJA9T5knUwWcBQD-747B5oyMx45FY0',
    appId: '1:299896259972:android:3c2c820ae615b9389849d1',
    messagingSenderId: '299896259972',
    projectId: 'gtms-fd7f3',
    databaseURL: 'https://gtms-fd7f3-default-rtdb.firebaseio.com',
    storageBucket: 'gtms-fd7f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFiiXKkoLyttdI-_Xv3Lw5GUnKX2yFTOk',
    appId: '1:299896259972:ios:63e7c9567f6bc2689849d1',
    messagingSenderId: '299896259972',
    projectId: 'gtms-fd7f3',
    databaseURL: 'https://gtms-fd7f3-default-rtdb.firebaseio.com',
    storageBucket: 'gtms-fd7f3.appspot.com',
    iosClientId:
        '299896259972-8b3ag83e6ud1jjue9jeq17n0jpb350s7.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFiiXKkoLyttdI-_Xv3Lw5GUnKX2yFTOk',
    appId: '1:299896259972:ios:63e7c9567f6bc2689849d1',
    messagingSenderId: '299896259972',
    projectId: 'gtms-fd7f3',
    databaseURL: 'https://gtms-fd7f3-default-rtdb.firebaseio.com',
    storageBucket: 'gtms-fd7f3.appspot.com',
    iosClientId:
        '299896259972-8b3ag83e6ud1jjue9jeq17n0jpb350s7.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtms',
  );
}
